version: '3'

services:
  teachteam-mysql-db:
    image: mysql:8.0
    container_name: recycling-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: recyclingteam
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_HOST: '%'